export default [
  {
    weaponName: "Axe, battle",
    damage: "1d6+1",
    weight: 15,
    cost: 7,
    handling: "two-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Axe, hand",
    damage: "1d6",
    weight: 5,
    cost: 3,
    handling: "one-handed",
    melee: true,
    missile: true,
    missileROF: 1,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Club",
    damage: "1d6",
    weight: 10,
    cost: 0,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: true,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Dagger",
    damage: "1d6-1",
    weight: 2,
    cost: 3,
    handling: "one-handed",
    melee: true,
    missile: true,
    missileROF: 1,
    cleric: false,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Flail",
    damage: "1d6",
    weight: 15,
    cost: 8,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: true,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Mace",
    damage: "1d6",
    weight: 10,
    cost: 5,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: true,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Morning Star",
    damage: "1d6",
    weight: 15,
    cost: 8,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: true,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Polearm",
    damage: "1d6+1",
    weight: 15,
    cost: 7,
    handling: "two-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Spear",
    damage: "1d6",
    weight: 10,
    cost: 2,
    handling: "one-handed",
    melee: true,
    missile: true,
    missileROF: 1,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Staff",
    damage: "1d6",
    weight: 10,
    cost: 1,
    handling: "two-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: false,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Sword, long",
    damage: "1d6",
    weight: 10,
    cost: 10,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Sword, short",
    damage: "1d6-1",
    weight: 5,
    cost: 8,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Sword, two-handed",
    damage: "1d6+1",
    weight: 15,
    cost: 15,
    handling: "two-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Warhammer",
    damage: "1d6",
    weight: 10,
    cost: 5,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    cleric: true,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Bow, long",
    damage: "1d6",
    weight: 5,
    cost: 40,
    handling: "two-handed",
    melee: false,
    missile: true,
    missileROF: 2,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Bow, short",
    damage: "1d6-1",
    weight: 5,
    cost: 25,
    handling: "two-handed",
    melee: false,
    missile: true,
    missileROF: 2,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Crossbow, heavy",
    damage: "1d6+1",
    weight: 5,
    cost: 25,
    handling: "two-handed",
    melee: false,
    missile: true,
    missileROF: 0.5,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Crossbow, light",
    damage: "1d6-1",
    weight: 5,
    cost: 15,
    handling: "two-handed",
    melee: false,
    missile: true,
    missileROF: 1,
    cleric: false,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    weaponName: "Sling",
    damage: "1d6",
    weight: 1,
    cost: 2,
    handling: "one-handed",
    melee: false,
    missile: true,
    missileROF: 1,
    cleric: true,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
];
