export default [
  {
    itemName: "Backpack (30 lb. capacity)",
    cost: 5,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Bedroll",
    cost: 2,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Belladonna, bunch",
    cost: 10,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Bottle (wine), glass",
    cost: 1,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Case (map or scroll)",
    cost: 3,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Crowbar",
    cost: 5,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Flint and Stell",
    cost: 5,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Garlic (1 lb.)",
    cost: 10,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Grappling Hook",
    cost: 5,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Hammer",
    cost: 2,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Helmet",
    cost: 10,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Holy Symbol, wooden",
    cost: 2,
    cleric: true,
    fighter: false,
    magicUser: false,
    thief: false,
    elf: false,
    repeatable: false,
  },
  {
    itemName: "Holy Symbol, silver",
    cost: 25,
    cleric: true,
    fighter: false,
    magicUser: false,
    thief: false,
    elf: false,
    repeatable: false,
  },
  {
    itemName: "Holy Water, small vial",
    cost: 25,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Lantern",
    cost: 10,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Mirror (small), steel",
    cost: 5,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Oil (lamp), 1 pint",
    cost: 2,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Pole, 10 ft.",
    cost: 1,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Rations, trail (day)",
    cost: 1,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Rations, dried (day)",
    cost: 3,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Rope (50 ft.), hemp",
    cost: 1,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Rope (50 ft.), silk",
    cost: 5,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Sack (15 lb. capacity)",
    cost: 1,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Sack (30 lb. capacity)",
    cost: 2,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Shovel",
    cost: 5,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Spellbook (blank)",
    cost: 100,
    cleric: false,
    fighter: false,
    magicUser: true,
    thief: false,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Spikes (12), iron",
    cost: 1,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Stakes (12), wooden",
    cost: 1,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Tent",
    cost: 20,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Thieves' Tools",
    cost: 25,
    cleric: false,
    fighter: false,
    magicUser: false,
    thief: true,
    elf: false,
    repeatable: false,
  },
  {
    itemName: "Torches (6)",
    cost: 1,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: true,
  },
  {
    itemName: "Waterskin",
    cost: 1,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
  {
    itemName: "Wolfsbane, bunch",
    cost: 10,
    cleric: true,
    fighter: true,
    magicUser: true,
    thief: true,
    elf: true,
    repeatable: false,
  },
];
