const ARMOR = [
  {
    armorName: "Unarmored",
    AC: 0,
    weight: 0,
    cost: 0,
    cleric: true,
    fighter: false,
    magicUser: true,
    thief: true,
    elf: true,
  },
  {
    armorName: "Chain Mail",
    AC: 4,
    weight: 50,
    cost: 30,
    cleric: true,
    fighter: true,
    magicUser: false,
    thief: false,
    elf: true,
  },
  {
    armorName: "Leather",
    AC: 2,
    weight: 25,
    cost: 15,
    cleric: true,
    fighter: true,
    magicUser: false,
    thief: true,
    elf: true,
  },
  {
    armorName: "Plate Mail",
    AC: 6,
    weight: 75,
    cost: 50,
    cleric: true,
    fighter: true,
    magicUser: false,
    thief: false,
    elf: false,
  },
];

const SHIELD = {
  armorName: "Shield",
  AC: 1,
  weight: 10,
  cost: 10,
  cleric: true,
  fighter: true,
  magicUser: false,
  thief: false,
  elf: true,
};

export { ARMOR, SHIELD };
