import { diceRoller } from "../System Neutral/functions.js";

const ELF_PRIME_ATTRIBUTES = ["STR", "INT"];

const MAGIC_USER_SPELLS_LEVEL_1 = [
  "Charm Person",
  "Detect Magic",
  "Hold Portal",
  "Light",
  "Protection from Chaos",
  "Read Languages",
  "Read Magic",
  "Sleep",
];

export const ADVENTURING_GEAR = [
  {
    itemName: "Backpack (30 lb. capacity)",
    cost: 5,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Bedroll",
    cost: 2,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Belladonna, bunch",
    cost: 10,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Bottle (wine), glass",
    cost: 1,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Case (map or scroll)",
    cost: 3,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Crowbar",
    cost: 5,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Flint and Stell",
    cost: 5,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Garlic (1 lb.)",
    cost: 10,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Grappling Hook",
    cost: 5,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Hammer",
    cost: 2,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Helmet",
    cost: 10,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Holy Symbol, wooden",
    cost: 2,
    usedBy: ["Cleric"],
    repeatable: false,
  },
  {
    itemName: "Holy Symbol, silver",
    cost: 25,
    usedBy: ["Cleric"],
    repeatable: false,
  },
  {
    itemName: "Holy Water, small vial",
    cost: 25,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Lantern",
    cost: 10,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Mirror (small), steel",
    cost: 5,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Oil (lamp), 1 pint",
    cost: 2,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Pole, 10 ft.",
    cost: 1,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Rations, trail (day)",
    cost: 1,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Rations, dried (day)",
    cost: 3,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Rope (50 ft.), hemp",
    cost: 1,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Rope (50 ft.), silk",
    cost: 5,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Sack (15 lb. capacity)",
    cost: 1,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Sack (30 lb. capacity)",
    cost: 2,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Shovel",
    cost: 5,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Spellbook (blank)",
    cost: 100,
    usedBy: ["Magic-User", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Spikes (12), iron",
    cost: 1,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Stakes (12), wooden",
    cost: 1,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Tent",
    cost: 20,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Thieves' Tools",
    cost: 25,
    usedBy: ["Thief"],
    repeatable: false,
  },
  {
    itemName: "Torches (6)",
    cost: 1,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: true,
  },
  {
    itemName: "Waterskin",
    cost: 1,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
  {
    itemName: "Wolfsbane, bunch",
    cost: 10,
    usedBy: ["Cleric", "Fighter", "Magic-User", "Thief", "Elf"],
    repeatable: false,
  },
];

export const ALIGNMENTS = ["Lawful", "Neutral", "Chaotic"];

export const ARMORS = [
  {
    armorName: "Unarmored",
    AC: 0,
    weight: 0,
    cost: 0,
    usedBy: ["Cleric", "Magic-User", "Thief", "Elf"],
  },
  {
    armorName: "Chain Mail",
    AC: 4,
    weight: 50,
    cost: 30,
    usedBy: ["Cleric", "Fighter", "Elf"],
  },
  {
    armorName: "Leather",
    AC: 2,
    weight: 25,
    cost: 15,
    usedBy: ["Cleric", "Fighter", "Thief", "Elf"],
  },
  {
    armorName: "Plate Mail",
    AC: 6,
    weight: 75,
    cost: 50,
    usedBy: ["Cleric", "Fighter"],
  },
];

export const CHARACTER_CLASSES = [
  {
    characterClassName: "Cleric",
    xpToLevel2: 1500,
    HDatLevel1: diceRoller(1, 6),
    toHitAtLevel1: 0,
    savingThrowAtLevel1: 15,
    savingThrowBonus: "+2 vs. death/poison",
    spellcasterType: "divine",
    primeAttribute: "WIS",
    domininonKind: "Temple",
    dominionLevel: 10,
    classSpecialAbilities: [`Turn the Undead`],
  },
  {
    characterClassName: "Fighter",
    xpToLevel2: 2000,
    HDatLevel1: diceRoller(1, 6) + 1,
    toHitAtLevel1: 0,
    savingThrowAtLevel1: 14,
    savingThrowBonus: "+2 vs. poison/paralysis",
    spellcasterType: null,
    spellsAtLevel1: null,
    primeAttribute: "STR",
    domininonKind: "Stronghold",
    dominionLevel: 9,
    classSpecialAbilities: [`Combat Fury (+1 attack/level vs. >=1 HD foes)`],
  },
  {
    characterClassName: "Elf",
    xpToLevel2: 5000,
    HDatLevel1: diceRoller(1, 6) + 1,
    toHitAtLevel1: 0,
    savingThrowAtLevel1: 14,
    savingThrowBonus: "+2 vs. poison/paralysis",
    spellcasterType: null, // TODO: change when implementing more character levels
    spellsAtLevel1: null,
    primeAttribute:
      ELF_PRIME_ATTRIBUTES[
        Math.floor(Math.random() * ELF_PRIME_ATTRIBUTES.length)
      ],
    classSpecialAbilities: [
      `+1 to-hit vs. goblins, orcs, intelligent undead, lycantropes`,
      `Immune to undead paralysis`,
      `Half damage from giants and ogres`,
      `4-in-6 chances of actively spotting hidden or concealed doors (2-in-6 if passing by)`,
    ],
  },
  {
    characterClassName: "Magic-User",
    xpToLevel2: 2500,
    HDatLevel1: diceRoller(1, 6),
    toHitAtLevel1: 0,
    savingThrowAtLevel1: 15,
    savingThrowBonus: "+2 vs. spells",
    spellcasterType: "magic",
    primeAttribute: "INT",
    domininonKind: "Wizard Tower",
    dominionLevel: 9,
    classSpecialAbilities: [
      `Known Spells: ${
        MAGIC_USER_SPELLS_LEVEL_1[
          Math.floor(Math.random() * MAGIC_USER_SPELLS_LEVEL_1.length)
        ]
      }`,
    ],
  },
  {
    characterClassName: "Thief",
    xpToLevel2: 1250,
    HDatLevel1: diceRoller(1, 6),
    toHitAtLevel1: 0,
    savingThrowAtLevel1: 14,
    savingThrowBonus: "+2 vs. Traps",
    spellcasterType: null,
    primeAttribute: "DEX",
    domininonKind: "Guild",
    dominionLevel: 9,
    classSpecialAbilities: [
      `Back Stab (+2 to Hit and x2 damage on hit)`,
      `Thievery 2-in-6`,
    ],
  },
];

export const SHIELDS = {
  armorName: "Shield",
  AC: 1,
  weight: 10,
  cost: 10,
  usedBy: ["Cleric", "Fighter", "Elf"],
};

export const WEAPONS = [
  {
    weaponName: "Axe, battle",
    damage: "1d6+1",
    weight: 15,
    cost: 7,
    handling: "two-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Axe, hand",
    damage: "1d6",
    weight: 5,
    cost: 3,
    handling: "one-handed",
    melee: true,
    missile: true,
    missileROF: 1,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Club",
    damage: "1d6",
    weight: 10,
    cost: 0,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Cleric", "Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Dagger",
    damage: "1d6-1",
    weight: 2,
    cost: 3,
    handling: "one-handed",
    melee: true,
    missile: true,
    missileROF: 1,
    usedBy: ["Fighter", "Magic-User", "Thief", "Elf"],
  },
  {
    weaponName: "Flail",
    damage: "1d6",
    weight: 15,
    cost: 8,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Cleric", "Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Mace",
    damage: "1d6",
    weight: 10,
    cost: 5,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Cleric", "Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Morning Star",
    damage: "1d6",
    weight: 15,
    cost: 8,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Cleric", "Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Polearm",
    damage: "1d6+1",
    weight: 15,
    cost: 7,
    handling: "two-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Spear",
    damage: "1d6",
    weight: 10,
    cost: 2,
    handling: "one-handed",
    melee: true,
    missile: true,
    missileROF: 1,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Staff",
    damage: "1d6",
    weight: 10,
    cost: 1,
    handling: "two-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Fighter", "Magic-User", "Thief", "Elf"],
  },
  {
    weaponName: "Sword, long",
    damage: "1d6",
    weight: 10,
    cost: 10,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Sword, short",
    damage: "1d6-1",
    weight: 5,
    cost: 8,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Sword, two-handed",
    damage: "1d6+1",
    weight: 15,
    cost: 15,
    handling: "two-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Warhammer",
    damage: "1d6",
    weight: 10,
    cost: 5,
    handling: "one-handed",
    melee: true,
    missile: false,
    missileROF: null,
    usedBy: ["Cleric", "Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Bow, long",
    damage: "1d6",
    weight: 5,
    cost: 40,
    handling: "two-handed",
    melee: false,
    missile: true,
    missileROF: 2,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Bow, short",
    damage: "1d6-1",
    weight: 5,
    cost: 25,
    handling: "two-handed",
    melee: false,
    missile: true,
    missileROF: 2,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Crossbow, heavy",
    damage: "1d6+1",
    weight: 5,
    cost: 25,
    handling: "two-handed",
    melee: false,
    missile: true,
    missileROF: 0.5,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Crossbow, light",
    damage: "1d6-1",
    weight: 5,
    cost: 15,
    handling: "two-handed",
    melee: false,
    missile: true,
    missileROF: 1,
    usedBy: ["Fighter", "Thief", "Elf"],
  },
  {
    weaponName: "Sling",
    damage: "1d6",
    weight: 1,
    cost: 2,
    handling: "one-handed",
    melee: false,
    missile: true,
    missileROF: 1,
    usedBy: ["Cleric", "Fighter", "Thief", "Elf"],
  },
];
